container:
  image: ubuntu:latest
  cpu: 4
  memory: 12G
task:
  install_script:
    - apt-get update && apt-get install -y python curl wget git
  script: |
    curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
